language: node_js

node_js:
  - 4
  - 6

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - PATH=$JAVA_HOME/bin:$PATH
  - java -version

after_failure:
  - pwd
  - find bin -type f -name "*.log*" -exec cat {} \;

sudo: false
