language: node_js

node_js:
  - 4
  - 6

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - PATH=$JAVA_HOME/bin:$PATH
  - java -version

after_failure:
  - cat bin/neo4j-community-3.0.0/logs/*

sudo: false
