language: node_js

node_js:
  - 4
  - 5

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - PATH=$JAVA_HOME/bin:$PATH
  - java -version

scripts:
  - npm test
  - cat /home/travis/build/catalint/neodb/bin/neo4j-community-3.0.0/logs/debug.log

sudo: false
